<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Interest_interest</name>
   <tag></tag>
   <elementGuidId>a74d0d45-1bcc-433d-a265-6247e5fe021b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='interest']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#interest</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>207b0f31-2b71-46db-9593-2031ac5df84d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>601cb3e6-4081-4b53-a37a-d2ce2677255a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2f2fc25d-39e8-444c-82f4-8d7ea25129f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Your interest</value>
      <webElementGuid>d85e0e53-a47d-41a9-832e-9cae28f0faaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>interest</value>
      <webElementGuid>dc17f50b-10bb-42dc-b2c3-2c93dd8f71d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>interest</value>
      <webElementGuid>0c4ab7a5-8d21-42fb-8c89-b2260c52cca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Entertaiment, Drama, Talent Search</value>
      <webElementGuid>ac6217a9-227f-4278-bcec-d8fb310c2001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3538881d-a4ba-4450-98ba-d4ffef3d8307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;interest&quot;)</value>
      <webElementGuid>56f0bbc2-efe2-4b1b-a007-ed7040b4a47c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='interest']</value>
      <webElementGuid>ca3a834b-777a-43f4-8716-a95abb3590f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='profile-ctn']/div[2]/div/div[2]/form/div[7]/input</value>
      <webElementGuid>18675a6a-a9ec-4398-bd49-e571020a6c97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>7be20630-1a54-44b9-b3fb-4ac3910dd2f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Your interest' and @id = 'interest' and @name = 'interest']</value>
      <webElementGuid>2b90a88a-959c-49fd-aa8a-5882ec6851d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
