<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>logo_rplus_di_homepage</name>
   <tag></tag>
   <elementGuidId>a7834c75-3813-4cdf-9ebc-fdaea9d57b7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Logo RCTI+']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.mb-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>48b0021f-2ba0-4777-8ac2-d7a1891dd52d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://rc-webdv2.rctiplus.com/assets/image/elements/svgv3/logo-nav-rcti.svg</value>
      <webElementGuid>edca4b35-a419-4d60-9208-1a9b4986ade1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-2</value>
      <webElementGuid>8d1b9d00-09ee-4991-a9fc-854d82501ed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>116.71px</value>
      <webElementGuid>b3d6390c-2974-42a4-935e-070cb5c4a6ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>39.88px</value>
      <webElementGuid>550a8d4e-4411-452b-8728-baab72699cdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Logo RCTI+</value>
      <webElementGuid>2e4068d7-bd0f-4a60-a3e9-11e119715d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;main-wrapper&quot;]/nav[@class=&quot;navbar navbar-icon-top navbar-expand-md bg-faded fixed-top&quot;]/a[@class=&quot;d-flex mr-auto&quot;]/img[@class=&quot;mb-2&quot;]</value>
      <webElementGuid>60cecb2b-f048-4991-95ea-b66688aa60eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Logo RCTI+']</value>
      <webElementGuid>7417e436-465d-4d61-9278-979a8e4c1a85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>8f2c2239-8835-4c7f-bccd-6abd8ea2769d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://rc-webdv2.rctiplus.com/assets/image/elements/svgv3/logo-nav-rcti.svg' and @alt = 'Logo RCTI+']</value>
      <webElementGuid>0da66b4b-f08f-4907-9b61-484013067774</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
