<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>logo_rplus_di_homepage</name>
   <tag></tag>
   <elementGuidId>a7834c75-3813-4cdf-9ebc-fdaea9d57b7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = 'https://rc-webdv2.rctiplus.com/assets/image/elements/svgv3/logo-nav-rcti.svg' and @alt = 'Logo RCTI+']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Logo RCTI+']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.mb-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fec14223-fd45-4458-8863-dc4be777a945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://rc-webdv2.rctiplus.com/assets/image/elements/svgv3/logo-nav-rcti.svg</value>
      <webElementGuid>bd4fba89-6201-48b1-9310-eab4b779b083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-2</value>
      <webElementGuid>e4a1d740-eb82-4813-98e4-28830a45955a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>116.71px</value>
      <webElementGuid>a78e9815-2968-4c8b-bfc3-b29087bd4b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>39.88px</value>
      <webElementGuid>4a69ec51-76f5-4b14-9992-d719a8011e6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Logo RCTI+</value>
      <webElementGuid>9c90cc50-971d-458a-afa0-3903533f8360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;main-wrapper&quot;]/nav[@class=&quot;navbar navbar-icon-top navbar-expand-md bg-faded fixed-top&quot;]/a[@class=&quot;d-flex mr-auto&quot;]/img[@class=&quot;mb-2&quot;]</value>
      <webElementGuid>7da34b97-5485-4726-9774-d418f5b6a5f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Logo RCTI+']</value>
      <webElementGuid>06d31b2f-00ca-460a-aef5-423c4d2501c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>d7ceac01-15a7-4e18-a2f5-26a489ab6917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://rc-webdv2.rctiplus.com/assets/image/elements/svgv3/logo-nav-rcti.svg' and @alt = 'Logo RCTI+']</value>
      <webElementGuid>ab9b9470-5553-418e-9966-41a08bc9726a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
