<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_profile</name>
   <tag></tag>
   <elementGuidId>01c4b622-027a-4a63-96ec-b48184b57e0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='profile_fud']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#profile_fud</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>02344a1b-586a-43c2-98e6-570eeb7c8ab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_fud</value>
      <webElementGuid>b0dd53a9-f0f0-4cee-8f4e-ee9b6d59d29d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-chevron-down</value>
      <webElementGuid>eeb248b5-a042-44eb-ab36-50a3a22074ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;main-wrapper&quot;]/nav[@class=&quot;navbar navbar-icon-top navbar-expand-md bg-faded fixed-top transparent-background&quot;]/div[@id=&quot;navbarSupportedContent&quot;]/ul[@class=&quot;navbar-nav&quot;]/li[@class=&quot;nav-item&quot;]/div[@id=&quot;profile_login&quot;]/div[@class=&quot;icon_wrap&quot;]/i[@id=&quot;profile_fud&quot;]</value>
      <webElementGuid>df5ab7de-e20f-4904-81c0-62a809a76fd1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='profile_fud']</value>
      <webElementGuid>f7af59a8-d59c-4eea-818a-7fefac0beb24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='profile_login']/div/i</value>
      <webElementGuid>dc0b82ab-3efd-4496-8638-23bebdbf6166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>4501985c-8c2a-4c7b-8571-a0e430e7f32e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'profile_fud']</value>
      <webElementGuid>584b61e4-f881-4c52-b471-fbdf847c18d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
