<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>alert_Your Nickname Has Been Taken</name>
   <tag></tag>
   <elementGuidId>6ba6ca0e-93e7-4985-8319-3feb32332833</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nickName']/div/div/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.message-error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ce2cf26f-5474-4492-a097-f2370e07faf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>message-error</value>
      <webElementGuid>654c60ad-1a61-446a-8666-ae9918453c78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your Nickname Has Been Taken</value>
      <webElementGuid>6ad62dff-366b-485c-8745-3f5da40ed92d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nickName&quot;)/div[@class=&quot;edit-profile&quot;]/div[@class=&quot;form-group&quot;]/span[@class=&quot;message-error&quot;]</value>
      <webElementGuid>4d8ed615-4d7d-4fac-a4de-700d917d2db1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nickName']/div/div/span[2]</value>
      <webElementGuid>9e467eab-9978-4144-957f-2a65254a236d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username has never been used with another user'])[1]/following::span[1]</value>
      <webElementGuid>27ec9a79-41e2-46ba-9b1c-cd9d84dbaaee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You may change your username back after 14 days'])[1]/following::span[1]</value>
      <webElementGuid>4defca1e-586c-426d-8c02-b0e277b74d53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::span[1]</value>
      <webElementGuid>5e8eeb6b-84f8-4494-b8d2-7c9dccc50f4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Profile'])[2]/preceding::span[1]</value>
      <webElementGuid>0a481dcb-0393-4fbe-90ce-7bc3c9ea81b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Your Nickname Has Been Taken']/parent::*</value>
      <webElementGuid>1636dc3c-d301-46cc-9c9a-200650c44c27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>d50c6492-bc5c-4019-bd92-7fa1414ccfaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Your Nickname Has Been Taken' or . = 'Your Nickname Has Been Taken')]</value>
      <webElementGuid>edd0b787-c943-4d31-ae6a-9f51bedd449e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
